/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * I2C-Generator: 0.3.0
 * Yaml Version: 0.1.0
 * Template Version: 0.7.0-62-g3d691f9
 */
/*
 * Copyright (c) 2021, Sensirion AG
 *
 * For licensing please refer to the LICENSE file of the repository.
 */

#ifndef SGP40_I2C_H
#define SGP40_I2C_H

#ifdef __cplusplus
extern "C" {
#endif

#include "sensirion_config.h"

/**
 * sgp40_measure_raw_signal() - This command starts/continues the VOC
 * measurement mode
 *
 * @param relative_humidity Leaves humidity compensation disabled by sending the
 * default value 0x8000 (50%RH) or enables humidity compensation when sending
 * the relative humidity in ticks (ticks = %RH * 65535 / 100)
 *
 * @param temperature Leaves humidity compensation disabled by sending the
 * default value 0x6666 (25 degC) or enables humidity compensation when sending
 * the temperature in ticks (ticks = (degC + 45) * 65535 / 175)
 *
 * @param sraw_voc u16 unsigned integer directly provides the raw signal
 * SRAW_VOC in ticks which is proportional to the logarithm of the resistance of
 * the sensing element.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sgp40_measure_raw_signal(uint16_t relative_humidity,
                                 uint16_t temperature, uint16_t* sraw_voc);

/**
 * sgp40_execute_self_test() - This command triggers the built-in self-test
 * checking for integrity of the hotplate and MOX material and returns the
 * result of this test as 2 bytes
 *
 * @param test_result 0xD4 00: all tests passed successfully or 0x4B 00: one or
 * more tests have failed
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sgp40_execute_self_test(uint16_t* test_result);

/**
 * sgp40_turn_heater_off() - This command turns the hotplate off and stops the
 * measurement. Subsequently, the sensor enters the idle mode.
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sgp40_turn_heater_off(void);

/**
 * sgp40_get_serial_number() - This command provides the decimal serial number
 * of the SGP40 chip by returning 3x2 bytes.
 *
 * @param serial_number 48-bit unique serial number
 *
 * @return 0 on success, an error code otherwise
 */
int16_t sgp40_get_serial_number(uint16_t* serial_number,
                                uint8_t serial_number_size);

#ifdef __cplusplus
}
#endif

#endif /* SGP40_I2C_H */
